Lint/UselessAssign:
  Excluded:
    - src/routes/*
    - src/server.cr
Lint/UnusedArgument:
  Excluded:
    - src/routes/*
Metrics/CyclomaticComplexity:
  Enabled: false
Layout/LineLength:
  Enabled: true
  MaxLength: 80
  Excluded:
    - src/routes/api.cr
